# ansible-playbook local.yml --ask-become-pass --ask-vault-pass
# ansible-playbook local.yml --ask-become-pass --vault-password-file ~/vault_pass.txt

- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/speed.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/iterm2.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/dotfiles.yml
