- hosts: localhost
  vars:
    user: roman
    dir: "/Users/{{ user }}/projects/ansible"
  tasks:
    - include_tasks: tasks/brew.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/dotfiles.yml
