- name: Check if Homebrew is installed
  stat:
    path: /usr/local/bin/brew
    register: brew_exists

- name: Install Homebrew
  command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  when: not brew_exists.stat.exists

- name: Update Homebrew
  command: brew update
  when: brew_exists.stat.exists
