- name: Install Core dependencies
  homebrew:
    name:
      - ninja
      - libtool
      - automake
      - cmake
      - pkg-config
      - gettext
      - curl
      - go
      - gopls
    state: present
