- name: Check if Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: brew_exists

# =============================================================================

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  when: not brew_exists.stat.exists

# =============================================================================

- name: Update Homebrew
  homebrew:
    update_homebrew: yes
  when: brew_exists.stat.exists

# =============================================================================

- name: Install Core Packages
  homebrew:
    name:
      - ninja
      - libtool
      - automake
      - cmake
      - gettext
      - curl
      - go
      - gopls
      - staticcheck
      - govulncheck
      #- goimports
      - golangci-lint
      - buf
      - kind
      - kubectl
      - kustomize
      # - pgcli
      - hey
      - fd
      - fzf
      - tmux
      - ripgrep
      - watch
      - stow
      - zsh
      - shfmt
      - git
    state: present
    install_options: skip-post-install
  when: ansible_facts['os_family'] == 'Darwin'

# =============================================================================

# - name: Install Docker
#   homebrew:
#     name: docker
#     cask: yes
#     state: present
#   when: ansible_facts['os_family'] == 'Darwin'
