- name: Install Stow
  homebrew: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Clone .dotfiles
  git:
    repo: "git@github.com:rkchv/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Get list of .dotfiles directories
  find:
    paths: "{{ lookup('env', 'HOME') }}/.dotfiles"
    file_type: directory
    depth: 1
  register: dotfiles_dirs
  tags: stow

- name: Stow all dotfiles
  shell: stow "{{ item.path | basename }}"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
  loop: "{{ dotfiles_dirs.files }}"
  tags:
    - install
    - dotfiles
    - stow

- name: Ensure tmux-sessionizer is executable
  file:
    path: "~/.local/scripts/tmux-sessionizer"
    mode: "0755"
    state: file

- name: Ensure tmux-cht.sh script is executable
  file:
    path: "~/.local/scripts/tmux-cht.sh"
    mode: "0755"
    state: file
