- name: Install stow
  homebrew: name=stow

- name: Clone .dotfiles
  command: cp -r "{{ dir }}/.dotfiles" "{{ lookup('env', 'HOME') }}/.dotfiles"
  tags: stow

- name: Get list of dotfile directories
  find:
    paths: "{{ lookup('env', 'HOME') }}/.dotfiles"
    file_type: directory
    depth: 1
  register: dotfiles_dirs
  tags: stow

- name: Stow all dotfiles
  command: stow "{{ item.path | basename }}"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
  loop: "{{ dotfiles_dirs.files }}"
  tags: stow
