- name: Check if the directory exists
  stat:
    path: "$HOME/lsp/lua-language-server"
  register: lua_ls_dir

- name: Clone the lua-language-server repository
  git:
    repo: https://github.com/sumneko/lua-language-server.git
    dest: "$HOME/lsp/lua-language-server"
  when: not lua_ls_dir.stat.exists

- name: Build the Lua language server
  command:
    cmd: ./make.sh
    chdir: "$HOME/lsp/lua-language-server"
  when: not lua_ls_dir.stat.exists

# =============================================================================

- name: Check if the directory exists
  stat:
    path: "$HOME/lsp/yaml-language-server"
  register: yaml_ls_dir

- name: Clone the yaml-language-server repository
  git:
    repo: https://github.com/redhat-developer/yaml-language-server.git
    dest: "$HOME/lsp/yaml-language-server"
  when: not yaml_ls_dir.stat.exists

# =============================================================================

- name: Check if the directory exists
  stat:
    path: "$HOME/lsp/bash-language-server"
  register: bash_ls_dir

- name: Link bash-language-server globally
  command: npm install -g bash-language-server --prefix "$HOME/lsp/bash-language-server"
  when: not bash_ls_dir.stat.exists
