- name: Remove neovim
  shell: rm -rf {{ lookup('env', 'HOME') }}/neovim

- name: Clone Neovim
  git:
    repo: "git@github.com:neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    update: true
    version: stable

- name: Compile neovim
  command:
    cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
    chdir: "{{ lookup('env', 'HOME') }}/neovim"

- name: Build neovim
  become: true
  command:
    cmd: make install
    chdir: "{{ lookup('env', 'HOME') }}/neovim"

