- name: Remove neovim
  shell: rm -rf ~/neovim

- name: Clone Neovim
  git:
    repo: "git@github.com:neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    update: yes
    version: stable
    accept_hostkey: yes

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 8"

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
